### ISSUE TITLE
R-hub builder says `NOTE: Package has help file(s) containing install/render-stage \Sexpr{} expressions but no prebuilt PDF manual.`

### ISSUE THREAD

**Issue by josephd000** [wviechtb/mathjaxr#15] opened 2022-06-24 18:55 UTC
## What I see

Three R-hub builder platforms out of three return a `NOTE, Package has help file(s) containing install/render-stage \Sexpr{} expressions but no prebuilt PDF manual.` and I expect that this will cause problems if I actually try to submit this package to CRAN with that NOTE.

## What I expect

That using `mathjaxr` package as described in the documentation will pass CRAN tests (and R-hub builder as well).

## Reproducible steps

I'm probably missing something obvious (or not following documentation) but here's what's happening ...

1. `devtools::create("../TestingMathJaxR")` and switch to that directory
2. `usethis::use_gpl3_license("My Name")`, `usethis::use_package("mathjaxr")`
3. Add `RdMacros: mathjaxr` to `DESCRIPTION` on line between `RoxygenNote: 7.2.0` and `Imports: mathjaxr` and change `email` under `Authors@R` to an email that R-hub builder recognizes
4. `usethis::edit_file("R/hello.R")`
5. Add a very small function to `R/hello.R`
    ```
    #' Title
    #' 
    #' \loadmathjax
    #' Description
    #' 
    #' @param arg1 arg1 details
    #' @param arg2 arg2 details
    #' 
    #' @details
    #' \mjtdeqn{B_{T,U} = REL_{T,U} - RES_{T,U) + UNC_{T,U}}{B_{T,U} = REL_{T,U} - RES_{T,U) + UNC_{T,U}}{... a plain text translation ...}
    #' 
    #' @return Sum
    #' @export
    #' @import mathjaxr
    #' 
    #' @examples
    #' \dontrun{
    #' testOut <-
    #'   testFunction(3, 2)
    #' }
    testFunction <- function(arg1, arg2) {
      out <- sum(arg1, arg2)

    return(out)
    }
    ```

7. `devtools::load_all(".")`, `devtools::document()`, `devtools::build()`
8. `devtools::check()` is 0 errors, 0 warnings, and 0 notes
9. `mathjaxr::preview_rd("man/testFunction.Rd", type = "pdf") looks good
10. devtools::check_rhub(platforms = "windows-x86_64-devel")` returns
    ```
    NOTE: Package has help file(s) containing install/render-stage \Sexpr{} expressions but no prebuilt PDF manual.
    ```

There are other NOTES too, but this is the note that affects my real package. I looked at other packages in the "Reverse imports" list on the mathjaxr CRAN page but don't see that they are having problems, so I'm wondering what I'm doing wrong.

## Resolutions attempted

- Adding `@noMd` tag just below `@export` tag
- Using `\mjdeqn` instead of `\mjtdeqn`
- Trying `\loadmathjax{}` instead of `\loadmathjax`

**Comment by wviechtb** [comment] 2022-07-09 07:48
I do not use `devtools`, `usethis`, `roxygen2`, or R-hub in my own package development workflow, but I tried to retrace your steps (for the most part), with some minor adjustments.

1. `usethis::use_gpl3_license("My Name")` gives an error, but `usethis::use_gpl3_license()` works so I used that.
2. In the equation, you have mismatched braces: `{T,U)`. I fixed that.
3. I needed to use `Description \loadmathjax` to avoid a note.
4. I put something real in the `person()` part in `DESCRIPTION`.

Then the package builds and the check generates no warnings or notes. Everything also looks as it should in the package dir. The package also installs fine and the equation is rendered properly. I even tested this under R-devel.

I did not check the package via R-hub, but all of the above works as it should and matches how things should be in comparison with several packages that I have successfully published via CRAN. So I would say for now that those R-hub notes are false positives. What specific platforms are generating those notes?

**Comment by rcalinjageman** [comment] 2024-03-14 14:50
I am having this same issue:

- I created a new package and followed the instructions to add mathjaxr
- I updated the 'hello' function to have roxygen documentation with a single equation
- When I check the package, even --as-cran I get no issues
- However, when I submit to rhub (using devtools::check_rhub())  I get "Package has help file(s) containing install/render-stage \Sexpr{} expressions but no prebuilt PDF manual."
- If I remove \loadmathjax and the equation, the error goes away.  If I remove the equation but leave \loadmathjax, the error is present -- so it doesn't seem to even need an equation to trigger the issue.
- I have experimented with different placements for the \loadmathjax command in the roxygen comments.  I've tried inserting this near the top of the documentation, as I've seen in the source code of several packages.  I've also tried putting it immediately after details.  I've tried various equations, pulling ones I could find in source code of different packages.  
- I can confirm that having this error in rhub means it will also appear in CRAN checks and that any submitted package with this issue gets rejected (believe me, I've been trying)

I've posted an minimal example here: https://github.com/rcalinjageman/mathjaxrtest

Sorry if this is something dumb I'm doing wrong.  I've been wrestling with this for several days, and no joy.  It's a pain to debug because I can't get it to happen locally, even with devtools::check_man(); so the only way to check is to submit to rhub which takes a good while).  I think, for the moment, I'm going to remove mathjaxr from a package I'm trying to get to CRAN.  

The description file is:


Package: mathjaxrtestused
Type: Package
Title: Tests for CRAN
Version: 0.1.0
Author: Robert Calin-Jageman
Maintainer: Robert Calin-Jageman <rcalinjageman@dom.edu>
Description: Tests for CRAN test problems when using 'mathjaxr'.
License: GPL-3
Encoding: UTF-8
Imports: 
    mathjaxr,
    roxygen2
RoxygenNote: 7.2.3
Roxygen: list(markdown = TRUE)
RdMacros: mathjaxr


And the hello function and roxygen comments is like this:

`
#' hello function
#'
#' @description \loadmathjax
#' description of hello function
#' \mjdeqn{k = log(1 - p) / log(1 - w^{n})}{k = log(1 - p) / log(1 - w^n)}
#'
#'
#' @details
#' Some details
#'
#'
#' @param  name person's name; defaults ot Bob
#'
#'
#' @return
#' Returns a character, name
#'
#'
#' @examples
#' hello("bob")
#'
#'
#' @importFrom stats qt
#' @export
hello <- function(name = "Bob") {
  print(
    paste(
      "Hello, world, and ",
      name,
      "!",
      sep = ""
    )
  )
  return(name)
}


fixrefs <- function() {
  roxygen2::block_get_tag()
  mathjaxr::preview_rd()
}
`

**Comment by wviechtb** [comment] 2024-03-14 15:20
I downloaded and tested the minimal example test package (thank you for providing this). `R CMD check --as-cran` does not flag any issues related to this. This is the check that an R package needs to pass and it does. You wrote "I can confirm that having this error in rhub means it will also appear in CRAN checks and that any submitted package with this issue gets rejected (believe me, I've been trying)". I have a hard time seeing how this is possible. Once the Rd files are generated via `roxygenise()`, they are part of the package (in the man directory) that is submitted as a tarball to CRAN. They are not further touched (unless one re-runs `roxygenise()` but CRAN doesn't do that AFAIK). So if the Rd files that are generated are fine (which they are, as otherwise the check above would flag any issues), then how can this then lead to any problems when submitting such a package to CRAN?

**Comment by rcalinjageman** [comment] 2024-03-14 21:25
Thanks.  I really don't understand this issue either.

I have a package I'm trying to get to CRAN that passes all local checks on my computer.   When checking with rhub, though, it generates the note about pdf manuals (and another about possible misspellings in the description file).  I thought these were ok to ignore, so I submitted to CRAN but got back this rejection: 

> Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-x86_64
> Check: CRAN incoming feasibility, Result: NOTE
>   Maintainer: 'Robert J Calin-Jageman <rcalinjageman@dom.edu>'
>   
>   New submission
>   
>   Possibly misspelled words in DESCRIPTION:
>     jamovi (7:31)
>     metafor (10:31)
>     statpsych (10:18, 14:5)
>   
>   Package has help file(s) containing install/render-stage \Sexpr{} expressions but no prebuilt PDF manual.

I put the 'misspelled' words in quotes and resubmitted and got a rejection again, just on the PDF error. 

In trying different things out with rhub, I found that the only way to get rid of the error was to remove alll use of mathjaxr in my roxygen comments.  Today, I submitted that way and it passed and is now under manual review (new package).  

I've tried a bunch of different things -- I thought I must have had an error in an equation, that I called \loadmathjax in the wrong place, that I had too many equations, etc... nothing seems to resolve the error on rhub (and by extension cran) despite everything checking out ok on my machine.  makes no sense, on obviously you're not having that problem submitting updates to your packages that use mathjaxr.  

For now, I'll live with documentation that doesn't have nice equations.  But I'll get back to trying to get this working in a bit.

**Comment by wviechtb** [comment] 2024-03-15 15:10
Yes, very strange. And you also have `import(mathjaxr)` in the `NAMESPACE` file?

**Comment by wviechtb** [comment] 2024-07-09 10:22
This issue has been discussed on the R-package-devel mailing list. See this thread: 

https://stat.ethz.ch/pipermail/r-package-devel/2024q3/010940.html

The solution is to add `BuildManual: TRUE` to the `DESCRIPTION` file and the note disappears. I have confirmed this.

**Comment by wviechtb** [comment] 2024-07-09 10:41
I've now also added this info the instructions. So closing this issue now.

**Closed as completed by wviechtb** 2024-07-09 10:41 UTC
